### ISSUE TITLE
bettertogether sql

### ISSUE THREAD

**Issue by cyberbsd** [bau720123/OpenCart_new#1]
Hi Bau,

Is sql table create for bettertogether missing?

Regards,
clarence

**Comment by bau720123** [comment]
hi @cyberbsd 
what are you mean about the sql table ?
my software is base on the "Better Together" extension
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=18124
and give the logical in the background instead of write some code in the "catalog\model\extension\total\better_together.php"

**Comment by cyberbsd** [comment]
Hi Bau,

Not sure if I misunderstand it.
But it looks like need an oc_bettertogether table in mysql ?
 
Regards,
Clarence

**Comment by bau720123** [comment]
hi @cyberbsd 
can you explain more detail ?
where you see the oc_bettertogether?
and..
why you think bettertogether table is missing?

**Comment by cyberbsd** [comment]
Hi Bau,

Seems 4 oc_bettertogether related tables
ref:
https://github.com/bau720123/OpenCart_new/blob/master/admin/model/marketing/bettertogether.php

https://github.com/bau720123/OpenCart_new/blob/master/catalog/model/extension/total/better_together.php
in setup()
There are two db query via oc_bettertogether oc_bettertogether_product oc_bettertogether_category

But I didn't find out where's the SQL describe about them.

Regards,
Clarence

**Comment by bau720123** [comment]
hi @cyberbsd 
oh !
the sql schema file not yet upload to the git because of some reason
I saw you are Taiwanese
I am too
maybe you may prefer use Chinese to talk to each other
